# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
mio = User.create(username: "miok", password: "password", firstname: "Mio", lastname: "Kataoka", pic:"./img/dray.jpg", contact:"5103568868")
aimee = User.create(username: "aimeek", password: "password", firstname: "Aimee", lastname: "Kalnoskas", pic:"./img/dray.jpg", contact:"5103568868")
molly = User.create(username: "mollyb", password: "password", firstname: "Molly", lastname: "Bergstrom", pic:"./img/dray.jpg", contact:"5103568868")
yui = User.create(username: "yuii", password: "password", firstname: "Yui", lastname: "Ikeda", pic:"./img/dray.jpg", contact:"5103568868")
fiona = User.create(username: "fionap", password: "password", firstname: "Fiona", lastname: "Peck", pic:"./img/dray.jpg", contact:"5103568868")
paul = User.create(username: "pauly", password: "password", firstname: "Paul", lastname: "Yen", pic:"./img/dray.jpg", contact:"5103568868")
louise = User.create(username: "louiser", password: "password", firstname: "Louise", lastname: "Rafkin", pic:"./img/dray.jpg", contact:"5103568868")
phyllis = User.create(username: "phyllisr", password: "password", firstname: "Phyllis", lastname: "Ritchie", pic:"./img/dray.jpg", contact:"5103568868")

dray = Dog.create(name:"Draymond", age: 4, breed: "Norwich", about:"Draymond is the mayor of the Dog Pod. He is the smallest of all members, but he can befriend any dog and he's always happy. Maybe it's his PR effort but we love his sunny disposition, plus he's so handsome!", user_id:mio.id, pic:"./img/dray.jpg")
axel = Dog.create(name:"Axel", age: 6, breed: "PWD", about:"Axel is a gentle giant living next door to Dray. As the oldest member of the Dog Pod he is very patient with the young ones, just as long as they are neutered...", user_id:phyllis.id, pic:"./img/axel.jpg" )
mugi = Dog.create(name:"Mugi", age: 2, breed: "Pomeranian", about:"Although supposedly a toy breed, Mugi is tireless and can handle big hikes and wild wrestling matches. He's somehow bigger than Dray, although he would submit to any dog within seconds. He tend to gain weight easily so he's perpetually dieting.", user_id:yui.id, pic:"./img/mugi.jpg" )
rose = Dog.create(name:"Rose", age: 2, breed: "Schnoodle", about:"Rose was adopted when she was one year old. Her original family never had a dog and didn't know how to raise her. She's also a COVID dog...meaning she never went outside, never met anyone outside of her initial family, never met a dog...until her original family decided to rehome her after the pandemic. Because of the lack of socialization and stimulation for the first year of her life, she doesn't know how to interact with dogs so careful supervision is needed.", user_id:molly.id, pic:"./img/rose.png" )
stella = Dog.create(name:"Stella", age: 3, breed: "mutt", about:"Stella was found roaming around in Richmond, but it took the rescue org over a month before they successfully captured her due to her extremely flightful nature. She shows signs of abuse by her former owner, so careful not to raise your voice or make sudden movements. She gets along with most dogs, but Clover does not like her and attacked her so they cannot be together unattended.", user_id:aimee.id, pic:"./img/stella.jpg" )
clover = Dog.create(name:"Clover", age: 4, breed: "Jindo", about:"Clover was rescued in Korea. True to the general temperament of Jindo, she's aloof and does not warm up to you easily, but once she does she's quite goofy. She has a string prey drive, and any dog showing signs of fear triggers her to be aggressive.", user_id:fiona.id, pic:"./img/clover.png" )
flo = Dog.create(name:"Florence", age: 5, breed: "mutt", about:"Flo was rescued from a hoarding situation. When she was surrendered, she was living with 10+ other dogs in a tiny and unsanitary one bedroom apartment. She is very needy and clingy, but as long as you cuddle and pet her there's little else she needs.", user_id:louise.id, pic:"./img/flo.jpg" )
pawblo = Dog.create(name:"Pawblo", age: 3, breed: "Husky-pitbull mix", about:"Although he's a rescue, Pawblo was born at the shelter and well cared for since the beginning. Thanks to that he's a very confident and happy boy who usually instigate the wild play time whenever the Dog Pod gathers.", user_id:paul.id, pic:"./img/pawblo.png" )

item1 = Item.create(name:"Small martingale collar", description: 'red martingale collar. Size small (about 10-12" long, 3/4" wide). Dray is too short and low to the ground and he keeps tripping over the loop. So it is not for him but hopefully someone can use it.', user_id:mio.id, pic:"./img/items/martingale.jpeg")
item2 = Item.create(name:"Flea Comb with a Double Row of Teeth", description: "Safari brand flea comb. It's very fine toothed so you need to brush your dog thoroughly before using this one. It works with any coat type and length. I thought I misplaced the one I had and bought another one. It's also perfect for combing out burrs after hiking.", user_id:phyllis.id, pic:"./img/items/fineComb.jpeg")
item3 = Item.create(name:"Pee pads", description: "I don't think Axel would need this anymore. two unopened bags of disposable pee pads. These pads are supposed to absorb up to three cups of urine and also control odors.", user_id:phyllis.id, pic:"./img/items/peepads.jpeg")
item4 = Item.create(name:"Small harness", description: "It still fits Dray but he just doesn't like it. Dray's neck girth is 12 inches and the chest is 20 inches. I know most of your dogs are bigger than Dray but if you know someone who can use it let me know!", user_id:mio.id, pic:"./img/items/harness.jpeg")
item5 = Item.create(name:"Bitter apple spray", description: "Non-toxic taste deterrent to discourage dogs from licking, gnawing and chewing. You can use it to protect your stuff, but might also be useful if your dog's itching and chewing their fur and skin. This is a refill bottle so you need a sprayer.  Spray on to the stuff you don't want your dog to chew on. Didn't work on Mugi though. The manufacturer also says you can use it to stop bad behaviors.", user_id:yui.id, pic:"./img/items/bitterApple.jpeg")
item6 = Item.create(name:"Soft nylon puppy collar", description: "Cute two-tobe nylon collar. It's soft and small (only up to 9 inches) so good for puppies. I wouldn't attach a leash and use it like a real collar.", user_id:yui.id, pic:"./img/items/puppycollar.jpeg")
item7 = Item.create(name:"Royal Canin Puppy Food", description: "A 30lb bag of puppy dry food. I love Royal Canin food but bought a puppy formula by mistake. I hope someone can use it. It's chicken and rice flavor. According to the packaging it's made for puppies up to 8 months old, with an expected adult weight of over 100lbs. I can deliver to your door if you want it.", user_id:molly.id, pic:"./img/items/puppyFood.jpeg")
item8 = Item.create(name:"Nylabone", description: "Two dog bone chew toys for ongoing entertainment and one chew treat for a satisfying reward. I thought if I get her something she's allowed to chew she'd leave my stuff alone but nope. It's a soft one so not for a power chewer. They might break it and swallow the bits.", user_id:molly.id, pic:"./img/items/nylabone.jpeg")
item9 = Item.create(name:"Mini tennis balls", description: "I won a dozen of them at an event. Unfortunately these don't have squeakers inside so Pawblo is not interested. Besides it's small so he might accidentally eat it. Each of them is in different colors and really cute.", user_id:paul.id, pic:"./img/items/tennisballs.jpeg")
item10 = Item.create(name:"Halloween costume (bumblebee, small)", description: "Clover used this when she was a puppy. it's size medium so probably too big for Dray and Mugi, but might work for Stella, Flo, or Rose. The head part is attached to the body like a hoodie. there's a strap that goes around the belly.", user_id:fiona.id, pic:"./img/items/costume.jpg")
item11 = Item.create(name:"Chunky sweater, large", description: "It says large but it's too small for Pawblo. I bought it at a post-christmas sale last year so it hasn't been used. It's Poly so you can toss it in a washer. There's a slit on the back side of the neck so you can attach leash to collar. ", user_id:paul.id, pic:"./img/items/chunkysweater.jpeg")
item12 = Item.create(name:"Training clickers", description: "If anyone wants to try clicker training I got a clicker. I had some success with Clover but I don't think we'll continue. It's got an elastic wrist band so you can leave it on your wrist or clip it to the leash. Supposedly you can use it with horses, cats, birds, etc.", user_id:fiona.id, pic:"./img/items/clickers.jpeg")
item13 = Item.create(name:"Topical flea control", description: "Frontline Plus kills fleas, flea eggs, lice, and ticks. It's waterproof and each dose lasts for a month. You dog needs to be older than 8 weeks. I've switched to tablet type. These cover between 89 - 132lbs dogs. Still got 4 months supply in the box.", user_id:louise.id, pic:"./img/items/frontline.jpeg")
item14 = Item.create(name:"Frisbees", description: "These are K-9 competition quality discs. You can easily make this fly over 80 yards, and you can use it at Hyperflite Skyhoundz World Canine Disc Champioship Series. I got a pack of 6 so happy to share. they are 9.6 x 9.6 x 4.4 inches and weighs 0.6kg each. ", user_id:yui.id, pic:"./img/items/frisbee.jpeg")
item15 = Item.create(name:"Toothbrush", description: "Finger-sack type toothbrushes. Some are silicone bristles, and others are nylon briftles. They are very soft so good for massaging gums, or for getting a puppy used to toothbrush too. Stella freaks out so much every time I try I'm resorting to just giving her greenies chews so you are welcome to have these.", user_id:aimee.id, pic:"./img/items/toothbrush.jpeg")
item16 = Item.create(name:"Dog cookie cutters", description: "If you are inspired to bake some home-made dog biscuits, I got these cookie cutters. They are bone, paw, dog, and a mystery shape (maybe supposed to be a dog house?) Someone gifted them to me last year but as you know I don't bake.", user_id:louise.id, pic:"./img/items/cookiecutters.jpeg")

tag1 = Tag.create(category:"walking")
tag2 = Tag.create(category:"food")
tag3 = Tag.create(category:"grooming")
tag4 = Tag.create(category:"puppy care")
tag5 = Tag.create(category:"play")

item_tags1 = ItemTag.create(item_id:item1.id, tag_id:tag4.id)
item_tags2 = ItemTag.create(item_id:item2.id, tag_id:tag3.id)
item_tags3 = ItemTag.create(item_id:item3.id, tag_id:tag4.id)
item_tags4 = ItemTag.create(item_id:item4.id, tag_id:tag1.id)
item_tags5 = ItemTag.create(item_id:item5.id, tag_id:tag4.id)
item_tags6 = ItemTag.create(item_id:item6.id, tag_id:tag1.id)
item_tags7 = ItemTag.create(item_id:item6.id, tag_id:tag1.id)
item_tags8 = ItemTag.create(item_id:item7.id, tag_id:tag2.id)
item_tags9 = ItemTag.create(item_id:item7.id, tag_id:tag4.id)
item_tags9 = ItemTag.create(item_id:item8.id, tag_id:tag5.id)
item_tags10 = ItemTag.create(item_id:item8.id, tag_id:tag4.id)
item_tags11 = ItemTag.create(item_id:item9.id, tag_id:tag4.id)
item_tags12 = ItemTag.create(item_id:item9.id, tag_id:tag5.id)
item_tags13 = ItemTag.create(item_id:item10.id, tag_id:tag1.id)
item_tags14 = ItemTag.create(item_id:item10.id, tag_id:tag5.id)
item_tags15 = ItemTag.create(item_id:item11.id, tag_id:tag1.id)
item_tags16 = ItemTag.create(item_id:item12.id, tag_id:tag1.id)
item_tags17 = ItemTag.create(item_id:item12.id, tag_id:tag4.id)
item_tags18 = ItemTag.create(item_id:item13.id, tag_id:tag3.id)
item_tags19 = ItemTag.create(item_id:item14.id, tag_id:tag5.id)
item_tags20 = ItemTag.create(item_id:item15.id, tag_id:tag3.id)
item_tags21 = ItemTag.create(item_id:item15.id, tag_id:tag4.id)
item_tags22 = ItemTag.create(item_id:item16.id, tag_id:tag2.id)
item_tags23 = ItemTag.create(item_id:item16.id, tag_id:tag4.id)

playdate1 = Playdate.create(when:"November 12th", howlong:"from 9 to noon-ish", user_id:aimee.id)
playdate2 = Playdate.create(when:"Any weekday afternoon so I can go to the city to run bunches of errands.", howlong:"about 3 hours", user_id:molly.id)
playdate3 = Playdate.create(when:"12/24-26th", howlong:"3 days, 2 nights", user_id:paul.id)
playdate4 = Playdate.create(when:"11/30 if I get selected for a jury duty", howlong:"not sure", user_id:louise.id)
playdate5 = Playdate.create(when:"12/13", howlong:"5p - 10:30", user_id:phyllis.id)
playdate6 = Playdate.create(when:"11/4", howlong:"all day", user_id:phyllis.id)
playdate7 = Playdate.create(when:"4 Mondays starting 11/21 while I'm in classes", howlong:"8am-4pm", user_id:yui.id)
playdate8 = Playdate.create(when:"12/28-1/1", howlong:"while I'm visiting my daughers", user_id:aimee.id)
playdate9 = Playdate.create(when:"11/5", howlong:"noon - 9pm", user_id:fiona.id)
playdate10 = Playdate.create(when:"November 18th", howlong:"about 4 hours", user_id:louise.id)